---
platforms:
  - name: docker-image
    transport:
      name: docker_cli
    driver:
      name: docker_cli
    driver_config:
      dockerfile: KitchenDockerfile
      # the just built image, those env variables are taken from imagerc file
      image: <%= ENV['AIT_DOCKER_IMAGE_NAME'] %>:<%= ENV['AIT_DOCKER_IMAGE_TAG'] %>
      # this does not work, so it is set in KitchenDockerfile:
      # entrypoint: /bin/bash
      # And you have to set command too. Reason:
      # http://gitlab.ai-traders.com/lab/ide/tree/master#ide-docker-image-release-cycle
      command: -c 'while true; do sleep 1d; done;'
      container_name: kt-gitide-image
      # mount dummy_work so that ide-fix-uid-gid.sh works
      # mount dummy_identity in order to not rely on real identity
      volume:
        - <%= File.dirname(__FILE__) %>/test/integration/dummy_work:/ide/work
        - <%= File.dirname(__FILE__) %>/test/integration/dummy_identity:/ide/identity

suites:
  - name: default
